### ISSUE TITLE
Please clarify copyright

### ISSUE THREAD

**Issue by elboulangero** [revel/config#9]
I'd like to package revel/config for Debian, however the copyright is not clear.

The readme states that the source files are distributed under the Mozilla Public License, while every source file claim to have an Apache license. The subdirectory `Doc` contains the Apache license. Is it an error in the Readme? Thanks.

**Comment by notzippy** [comment]
to clarify the readme says
```
The source files are distributed under the Mozilla Public License, version 2.0, unless otherwise noted.
```
The key being `unless otherwise noted`, since the source files have `http://www.apache.org/licenses/LICENSE-2.0` in the headings I would say that license supersedes the README file 

Sorry I cannot be  more help here - the original [author](https://github.com/robfig/config) may be of more help. But he has not been available for a number of years that is why we cloned the repo here.

**Comment by elboulangero** [comment]
Thanks for the explanation
